data_type: image
repo_path: ./
save_name: image_debug

batch_size: 32
test_batch_size: 100
lr: 0.001
momentum: 0.9
decay: 0.0005
total_rounds: 999
optimizer: SGD

scratch: false
only_eval: false
partial_test: 10
multi_gpu: false

freeze_base: false

ewc: false
lamb: 5000
resumed_fisher: /home/ty367/federated/data/cifar_median_fisher.pt

kd: false
alpha: 0.95
temperature: 6

recreate_dataset: false

resumed_model: model_image_Nov.09_01.55.54/model_last.pt.tar.best
###averaging: model_image_Nov.09_01.58.58/model_last.pt.tar.best
###averaging_diff: model_image_Nov.09_01.59.42/model_last.pt.tar.best
###median: model_image_Nov.09_01.55.54/model_last.pt.tar.best

# import for Federated Learning
number_of_total_participants: 100
no_models: 100
retrain_no_times: 200
eta: 1

log: True
tb: True

random: False