batch_size: 32
test_batch_size: 100
lr: 0.001
### 0.1, 0.01, 0.001
momentum: 0.9
decay: 0.0005
epochs: 999
save_on_epochs: []
optimizer: SGD
log_interval: 20

save_name: /home/ty367/federated/log/image_scratch1
scratch: true
only_eval: false
freeze_base: false
partial_test: 10
multi_gpu: false
ewc: false
lamb: 5000
resumed_fisher: /home/ty367/federated/data/cifar_median_fisher.pt

kd: false
alpha: 0.95
temperature: 6

save_model: false
scheduler: False
recreate_dataset: false
sampling_dirichlet: true
dirichlet_alpha: 0.9

# resumed_model: model_image_Nov.09_01.55.54/model_last.pt.tar.best
###averaging: model_image_Nov.09_01.58.58/model_last.pt.tar.best
###averaging_diff: model_image_Nov.09_01.59.42/model_last.pt.tar.best
###median: model_image_Nov.09_01.55.54/model_last.pt.tar.best

diff_privacy: false
s_norm: 15
sigma: 0.01

data_type: image

# import for Federated Learning
aggregation_type: averaging
### averaging, median
number_of_total_participants: 100
no_models: 100
retrain_no_times: 500
eta: 10

log: True
tb: True

report_train_loss: True

random: False