batch_size: 32
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
epochs: 999
save_on_epochs: []
optimizer: SGD
log_interval: 20

only_eval: False
freeze_base: false
partial_test: 10
multi_gpu: false
ewc: false
lamb: 5000
resumed_fisher: /home/ty367/federated/data/cifar_fisher.pt

kd: true
alpha: 0.95
temperature: 6

save_model: false
scheduler: False
recreate_dataset: False

resumed_model: model_image_Nov.03_14.42.07/model_last.pt.tar.best
###private: model_image_Nov.03_14.42.07/
###non-private: model_image_Oct.29_17.41.26/

diff_privacy: false
s_norm: 15
sigma: 0.01

data_type: image

# import for Federated Learning
number_of_total_participants: 100
no_models: 99
retrain_no_times: 100
eta: 10

log: True
tb: True

report_train_loss: True

random: False